// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtwmhiyajmnegaqewkgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0d21oaXlham1uZWdhcWV3a2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MjkwNzUsImV4cCI6MjA1NTUwNTA3NX0.Jxy4Ye2n2Ni8Qucnftew-2emyT-jNcDdjwEIcV5cvJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);